# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup  # type: ignore
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="powerk8s",
    version="0.1.0",
    description="Powerline Segment for Kubernetes",
    python_requires="==3.*,>=3.7.0",
    author="George Kontridze",
    author_email="george.kontridze@gmail.com",
    license="MIT",
    entry_points={"console_scripts": ["lint = scripts.lint:main"]},
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "kubernetes==12.*,>=12.0.1",
        "powerline-status==2.*,>=2.7.0",
        "pyyaml==5.*,>=5.3.1",
    ],
    extras_require={
        "dev": [
            "autoflake==1.*,>=1.4.0",
            "black==20.*,>=20.8.0.b1",
            "dephell==0.*,>=0.8.3",
            "ipython==7.*,>=7.19.0",
            "isort==5.*,>=5.6.4",
            "mypy==0.*,>=0.790.0",
            "toml==0.*,>=0.10.2",
        ]
    },
)
