---
name: CI

on: [push, pull_request, workflow_call]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Configure dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip3 install -U poetry

      - name: Install dependencies
        run: poetry install

      - name: Run multilint on itself
        run: poetry run multilint
