---
name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: pip3 install -U pip

      - name: Install Poetry
        run: pip3 install -U poetry

      - name: Set up dependencies
        run: poetry install

      - name: Run linters
        run: poetry run multilint

      - name: Run unit tests
        run: poetry run python -m unittest -v
