---
name: Release

on:
  push:
    branches: [master]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Configure dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: pip3 install -U pip

      - name: Install Poetry
        run: pip3 install -U poetry

      - name: Install dependencies
        run: poetry install

      - name: Build artifacts
        run: poetry build

      - name: Create GitHub Release
        run: gh release create $(poetry version -s) dist/*
        env:
          GH_TOKEN: ${{ secrets.ACTIONS }}

      - name: Upload release artifacts to PyPI
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPITOKEN }}
