---
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      
      - name: Upgrade pip
        run: pip3 install -U pip

      - name: Install Poetry
        run: pip3 install -U poetry

      - name: Install dependencies
        run: poetry install

      - name: Build artifacts
        run: poetry build

      - name: Create GitHub Release
        run: gh release create $(poetry version -s) dist/*
        env:
          GH_TOKEN: ${{ secrets.ACTIONS }}
      
      - name: Upload artifacts to PyPI
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPITOKEN }}
